name: Weekly Coding Challenges Email

on:
  workflow_dispatch

jobs:
  send_email:
    runs-on: ubuntu-latest
    env:
      EMAIL_USER: ${{ secrets.EMAIL_USER }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
    - name: Run Python script
      run: python main.py
    - name: Commit indices file
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add indices.json
        git commit -m "Update indices for coding challenges"
        git push
