name: Weekly Coding Challenges Email

on:
  schedule:
    - cron: '0 2 * * *'  #테스트기간 이틀동안만 매일 오전 11시에 이메일 발송되도록 설정

jobs:
  send_email:
    runs-on: ubuntu-latest
    env:
      EMAIL_USER: ${{ secrets.EMAIL_USER }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.MY_TOKEN }}
    - name: Check current directory
      run: pwd
    - name: List files in the directory
      run: ls -lah
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
    - name: Run Python script
      run: python main.py
    - name: Commit indices file
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add indices.json
        if [ -z "$(git status --porcelain)" ]; then
          echo "No changes to commit."
          exit 0
        fi
        git commit -m "Update indices for coding challenges"
        git push
