name: Weekly Coding Challenges Email

on:
  schedule:
    - cron: '40 13 * * 3'  # UTC 시간 기준, KST로는 수요일 22시 40분

jobs:
  send_email:
    runs-on: ubuntu-latest
    env:
      EMAIL_USER: ${{ secrets.EMAIL_USER }}  # GitHub Secrets에서 설정한 이메일 사용자명
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}  # GitHub Secrets에서 설정한 이메일 비밀번호
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
    - name: Run the script
      run: python main.py
