name: Weekly Python Script

on:
  schedule:
    - cron: '40 22 * * 3'  # 매주 수요일 22시 40분에 실행

jobs:
  run_script:
    runs-on: ubuntu-latest
    env:
      KAKAO_TOKEN: ${{ secrets.KAKAO_REST_API_KEY }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # 필요한 Python 버전 지정
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # 필요한 패키지 설치
    - name: Run script
      run: python main.py  # 실행할 스크립트 파일 이름
