name: Weekly Python Script

on:
  schedule:
    - cron: '10 22 * * 3'  # 매주 월요일 0시 5분에 실행

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # 필요한 Python 버전 지정
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # 필요한 패키지 설치
    - name: Run script
      run: python your_script.py  # 실행할 스크립트 파일 이름
