name: Weekly Coding Challenges Email

on:
  schedule:
    - cron: '*/60 * * * *'

jobs:
  send_email:
    runs-on: ubuntu-latest
    env:
      EMAIL_USER: ${{ secrets.EMAIL_USER }}  # GitHub Secrets에서 설정한 이메일 사용자명
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}  # GitHub Secrets에서 설정한 이메일 비밀번호
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
    - name: Run Python script
      run: python main.py
